services:
  app:
    image: kevinduy/amazonlinnux1
    build: .
    tty: true
    restart: always
    volumes:
      - ./app:/var/www/app
    ports:
      - "80:80"
      - "433:443"
    environment:
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTPS_PROXY}
      - CHOKIDAR_USEPOLLING=true
      - AWS_DEFAULT_OUTPUT=${AWS_DEFAULT_OUTPUT}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
